version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - run:
          name: Generate cumulative pom.xml checksum
          command : |
            find . -type f -name "pom.xml" -exec sh -c "sha256sum {} >> ~/pom-checksum.tmp" \;
            sort -o ~/pom-checksum ~/pom-checksum.tmp
          when: always
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "~/pom-checksum" }}

      -run: mvn package

      - store_test_results:
          path: target/surefire-reports

      -store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
          